import { ArtworkSearchItem } from "@shared/api/search";

export const searchDummy: ArtworkSearchItem[] = [
  {
    artworkId: "dummy_1",
    originalTitle: "국립중앙박물관",
    korTitle: "국립중앙박물관",
    enTitle: "National Museum of Korea",
    originalArtist: "",
    korArtist: "",
    enArtist: "",
    imageUrl: "https://cdn.safetimes.co.kr/news/photo/202106/96480_77112_1213.jpg",
    score: 0,
  },
  {
    artworkId: "dummy_2",
    originalTitle: "인상주의",
    korTitle: "인상주의",
    enTitle: "Impressionism",
    originalArtist: "",
    korArtist: "",
    enArtist: "",
    imageUrl: "https://cdn.safetimes.co.kr/news/photo/202106/96480_77112_1213.jpg",
    score: 0,
  },
  {
    artworkId: "dummy_3",
    originalTitle: "MOMA",
    korTitle: "MOMA",
    enTitle: "MOMA",
    originalArtist: "",
    korArtist: "",
    enArtist: "",
    imageUrl: "https://cdn.safetimes.co.kr/news/photo/202106/96480_77112_1213.jpg",
    score: 0,
  },
  {
    artworkId: "dummy_4",
    originalTitle: "모네",
    korTitle: "모네",
    enTitle: "Monet",
    originalArtist: "Claude Monet",
    korArtist: "클로드 모네",
    enArtist: "Claude Monet",
    imageUrl: "https://cdn.safetimes.co.kr/news/photo/202106/96480_77112_1213.jpg",
    score: 0,
  },
  {
    artworkId: "dummy_5",
    originalTitle: "르누아르",
    korTitle: "르누아르",
    enTitle: "Renoir",
    originalArtist: "Pierre-Auguste Renoir",
    korArtist: "르누아르",
    enArtist: "Pierre-Auguste Renoir",
    imageUrl: null,
    score: 0,
  },
  {
    artworkId: "dummy_6",
    originalTitle: "르네상스",
    korTitle: "르네상스",
    enTitle: "Renaissance",
    originalArtist: "",
    korArtist: "",
    enArtist: "",
    imageUrl: "https://cdn.safetimes.co.kr/news/photo/202106/96480_77112_1213.jpg",
    score: 0,
  },
  {
    artworkId: "dummy_7",
    originalTitle: "초현실주의",
    korTitle: "초현실주의",
    enTitle: "Surrealism",
    originalArtist: "",
    korArtist: "",
    enArtist: "",
    imageUrl: null,
    score: 0,
  },
  {
    artworkId: "dummy_8",
    originalTitle: "현대미술",
    korTitle: "현대미술",
    enTitle: "Contemporary Art",
    originalArtist: "",
    korArtist: "",
    enArtist: "",
    imageUrl: null,
    score: 0,
  },
];
