import { ArtworkSearchItem } from "@shared/api/search";

export const searchDummy: ArtworkSearchItem[] = [
  {
    artworkId: "dummy_1",
    korTitle: "클로드 모네",
    originalTitle: "Claude Monet",
    enTitle: "Claude Monet",
    korArtist: "클로드 모네",
    originalArtist: "Claude Monet",
    enArtist: "Claude Monet",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/88/Claude_Monet_1899_Nympheas.jpg",
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_2",
    korTitle: "파블로 피카소",
    originalTitle: "Pablo Picasso",
    enTitle: "Pablo Picasso",
    korArtist: "파블로 피카소",
    originalArtist: "Pablo Picasso",
    enArtist: "Pablo Picasso",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/7/74/PicassoGuernica.jpg",
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_3",
    korTitle: "에두아르 마네",
    originalTitle: "Édouard Manet",
    enTitle: "Édouard Manet",
    korArtist: "에두아르 마네",
    originalArtist: "Édouard Manet",
    enArtist: "Édouard Manet",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/88/Edouard_Manet_-_Olympia_-_Google_Art_Project_3.jpg",
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_4",
    korTitle: "살바도르 달리",
    originalTitle: "Salvador Dalí",
    enTitle: "Salvador Dalí",
    korArtist: "살바도르 달리",
    originalArtist: "Salvador Dalí",
    enArtist: "Salvador Dalí",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/1/1d/The_Persistence_of_Memory.jpg",
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_5",
    korTitle: "프란시스코 고야",
    originalTitle: "Francisco Goya",
    enTitle: "Francisco Goya",
    korArtist: "프란시스코 고야",
    originalArtist: "Francisco Goya",
    enArtist: "Francisco Goya",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0b/El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_in_Google_Earth.jpg",
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_6",
    korTitle: "앙리 마티스",
    originalTitle: "Henri Matisse",
    enTitle: "Henri Matisse",
    korArtist: "앙리 마티스",
    originalArtist: "Henri Matisse",
    enArtist: "Henri Matisse",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/1/1c/Henri_Matisse_Woman_with_a_Hat.jpg",
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_7",
    korTitle: "앤디워홀",
    originalTitle: "Andy Warhol",
    enTitle: "Andy Warhol",
    korArtist: "앤디 워홀",
    originalArtist: "Andy Warhol",
    enArtist: "Andy Warhol",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/0/0a/Marilyn_Diptych.jpg",
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_8",
    korTitle: "에드가 드가",
    originalTitle: "Edgar Degas",
    enTitle: "Edgar Degas",
    korArtist: "에드가 드가",
    originalArtist: "Edgar Degas",
    enArtist: "Edgar Degas",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Edgar_Germain_Hilaire_Degas_069.jpg",
    score: 0,
    isLiked: false,
  },
];
