import { ArtworkSearchItem } from "@shared/api/search";

import recommended_search_thumbnail_monet from '@/assets/recommendations/recommended_search_thumbnail_monet.jpg';
import recommended_search_thumbnail_picaso from '@/assets/recommendations/recommended_search_thumbnail_picaso.jpg';
import recommended_search_thumbnail_manet from '@/assets/recommendations/recommended_search_thumbnail_manet.jpg';
import recommended_search_thumbnail_dali from '@/assets/recommendations/recommended_search_thumbnail_dali.jpg';
import recommended_search_thumbnail_goya from '@/assets/recommendations/recommended_search_thumbnail_goya.jpg';    
import recommended_search_thumbnail_matisse from '@/assets/recommendations/recommended_search_thumbnail_matisse.jpg';
import recommended_search_thumbnail_warhol from '@/assets/recommendations/recommended_search_thumbnail_warhol.jpg';
import recommended_search_thumbnail_degas from '@/assets/recommendations/recommended_search_thumbnail_degas.jpg';
import recommended_search_thumbnail_chagall from '@/assets/recommendations/recommended_search_thumbnail_chagall.jpg';
import recommended_search_thumbnail_mondrian from '@/assets/recommendations/recommended_search_thumbnail_mondrian.jpg';
import recommended_search_thumbnail_kahlo from '@/assets/recommendations/recommended_search_thumbnail_kahlo.jpg';
import recommended_search_thumbnail_malevich from '@/assets/recommendations/recommended_search_thumbnail_malevich.jpg';
import recommended_search_thumbnail_hockney from '@/assets/recommendations/recommended_search_thumbnail_hockney.jpg';
import recommended_search_thumbnail_pissarro from '@/assets/recommendations/recommended_search_thumbnail_pissarro.jpg';
import recommended_search_thumbnail_gauguin from '@/assets/recommendations/recommended_search_thumbnail_gauguin.jpg';
import recommended_search_thumbnail_klimt from '@/assets/recommendations/recommended_search_thumbnail_klimt.jpg';



export const searchDummy: ArtworkSearchItem[] = [
  {
    artworkId: "dummy_1",
    korTitle: "클로드 모네",
    originalTitle: "Claude Monet",
    enTitle: "Claude Monet",
    korArtist: "클로드 모네",
    originalArtist: "Claude Monet",
    enArtist: "Claude Monet",
    imageUrl: recommended_search_thumbnail_monet,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_2",
    korTitle: "파블로 피카소",
    originalTitle: "Pablo Picasso",
    enTitle: "Pablo Picasso",
    korArtist: "파블로 피카소",
    originalArtist: "Pablo Picasso",
    enArtist: "Pablo Picasso",
    imageUrl: recommended_search_thumbnail_picaso,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_3",
    korTitle: "에두아르 마네",
    originalTitle: "Édouard Manet",
    enTitle: "Édouard Manet",
    korArtist: "에두아르 마네",
    originalArtist: "Édouard Manet",
    enArtist: "Édouard Manet",
    imageUrl: recommended_search_thumbnail_manet,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_4",
    korTitle: "살바도르 달리",
    originalTitle: "살바도르 달리",
    enTitle: "Salvador Dalí", 
    korArtist: "살바도르 달리",
    originalArtist: "살바도르 달리", 
    enArtist: "Salvador Dalí",
    imageUrl: recommended_search_thumbnail_dali,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_5",
    korTitle: "프란시스코 고야",
    originalTitle: "Francisco Goya",
    enTitle: "Francisco Goya",
    korArtist: "프란시스코 고야",
    originalArtist: "Francisco Goya",
    enArtist: "Francisco Goya",
    imageUrl: recommended_search_thumbnail_goya,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_6",
    korTitle: "앙리 마티스",
    originalTitle: "Henri Matisse",
    enTitle: "Henri Matisse",
    korArtist: "앙리 마티스",
    originalArtist: "Henri Matisse",
    enArtist: "Henri Matisse",
    imageUrl: recommended_search_thumbnail_matisse,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_7",
    korTitle: "앤디 워홀",
    originalTitle: "Andy Warhol",
    enTitle: "Andy Warhol",
    korArtist: "앤디 워홀",
    originalArtist: "Andy Warhol",
    enArtist: "Andy Warhol",
    imageUrl: recommended_search_thumbnail_warhol,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_8",
    korTitle: "에드가 드가",
    originalTitle: "Edgar Degas",
    enTitle: "Edgar Degas",
    korArtist: "에드가 드가",
    originalArtist: "Edgar Degas",
    enArtist: "Edgar Degas",
    imageUrl: recommended_search_thumbnail_degas,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_9",
    korTitle: "마르크 샤갈",
    originalTitle: "Marc Chagall",
    enTitle: "Marc Chagall",
    korArtist: "마르크 샤갈",
    originalArtist: "Marc Chagall",
    enArtist: "Marc Chagall",
    imageUrl: recommended_search_thumbnail_chagall,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_10",
    korTitle: "피에트 몬드리안",
    originalTitle: "Piet Mondrian",
    enTitle: "Piet Mondrian",
    korArtist: "피에트 몬드리안",
    originalArtist: "Piet Mondrian",
    enArtist: "Piet Mondrian",
    imageUrl: recommended_search_thumbnail_mondrian,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_11",
    korTitle: "프리다 칼로",
    originalTitle: "Frida Kahlo",
    enTitle: "Frida Kahlo",
    korArtist: "프리다 칼로",
    originalArtist: "Frida Kahlo",
    enArtist: "Frida Kahlo",
    imageUrl: recommended_search_thumbnail_kahlo,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_12",
    korTitle: "카지미르 말레비치",
    originalTitle: "Kazimir Malevich",
    enTitle: "Kazimir Malevich",
    korArtist: "카지미르 말레비치",
    originalArtist: "Kazimir Malevich",
    enArtist: "Kazimir Malevich",
    imageUrl: recommended_search_thumbnail_malevich,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_13",
    korTitle: "데이비드 호크니",
    originalTitle: "David Hockney",
    enTitle: "David Hockney",
    korArtist: "데이비드 호크니",
    originalArtist: "David Hockney",
    enArtist: "David Hockney",
    imageUrl: recommended_search_thumbnail_hockney,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_14",
    korTitle: "카미유 피사로",
    originalTitle: "Camille Pissarro",
    enTitle: "Camille Pissarro",
    korArtist: "카미유 피사로",
    originalArtist: "Camille Pissarro",
    enArtist: "Camille Pissarro",
    imageUrl: recommended_search_thumbnail_pissarro,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_15",
    korTitle: "폴 고갱",
    originalTitle: "Paul Gauguin",
    enTitle: "Paul Gauguin",
    korArtist: "폴 고갱",
    originalArtist: "Paul Gauguin",
    enArtist: "Paul Gauguin",
    imageUrl: recommended_search_thumbnail_gauguin,
    score: 0,
    isLiked: false,
  },
  {
    artworkId: "dummy_16",
    korTitle: "구스타브 클림트",
    originalTitle: "Gustav Klimt",
    enTitle: "Gustav Klimt",
    korArtist: "구스타브 클림트",
    originalArtist: "Gustav Klimt",
    enArtist: "Gustav Klimt",
    imageUrl: recommended_search_thumbnail_klimt,
    score: 0,
    isLiked: false,
  },
];
